language: 
  php

php: 
  - 5.4
  - 5.5
  - hhvm

env:
  - NODE_JS_VERSION=4
  - BUILD=with-tests

branches:
  only:
  - travis_ci

before_script:
  - "export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH"
  - "echo $(pwd) && ls && ls www"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - npm install -g brunch@2.9.1
  - npm install -g bower
  - npm install
  - bower update
  - sleep 1

script: npm test
