language: 
  node_js

node_js:
  - 5.11
  - 4.2

env:
  - BUILD=with-tests

branches:
  only:
  - master

before_script:
  - "export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - npm install -g brunch
  - npm install -g bower
  - npm install
  - bower install
  - bower update
  - sleep 1
  - BUILD=with-tests brunch b

script: phantomjs www/demo/
