language: 
  php

php: 
  - 5.4
  - hhvm

env:
  - TRAVIS_NODE_VERSION="4"

sudo: false

branches:
  only:
  - travis_ci

allow_failures:
  - php: hhvm

before_script:
  - "export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH"
  - "echo $(pwd) && ls && ls www"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@4; fi

install:
  - npm install -g brunch@2.9.1
  - npm install -g bower
  - npm install
  - bower update
  - BUILD=with-tests brunch b
  - sleep 1

script: npm test
