language: 
  php

php: 
  - 5.4

env:
  global:
    - NODE_VERSION="4"
    - NODE_JS_VERSION="4"
    - TRAVIS_NODE_VERSION="4"

addons:
  hosts:
    - localhost

sudo: required

branches:
  only:
  - travis_ci

before_install:
  - uname -a
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - nvm install node

install:
  - npm install -g brunch@2.9.1
  - npm install -g bower
  - npm install
  - bower update
  - sleep 1

before_script:
  - "export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH"
  - export HOSTNAME=localhost
  - cd www
  - "echo $(pwd) && ls"
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f ../build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo sed -e "s?Listen 80?Listen 8080?g" --in-place /etc/apache2/ports.conf
  - echo "ServerName localhost" | sudo tee -a /etc/apache2/httpd.conf
  - sudo service apache2 restart
  # log useful debugging info
  - sudo apachectl configtest
  - sudo ls /etc/apache2/
  - sudo cat /etc/apache2/httpd.conf
  - sudo cat /etc/apache2/sites-available/default
  - sudo apachectl fullstatus | tail -1
  - sudo netstat -anp | grep apache2
  # back to root dir, we will run test from there
  - cd ..
  - sleep 1

script: npm test
